- packages/wujie-core/__test__/unit/utils.test.ts
- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/entry.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/utils.ts
- packages/wujie-doc/docs/guide/plugin.md
相关 isssue：https://github.com/Tencent/wujie/issues/20
目标：支持更加灵活的 jsExcludes 和 cssExcludes
大佬先看以下改动的时候可以，如果可以，我再补充以下测试用例
> feat: jsExcludes 和 cssExcludes 支持正则

- examples/main-react/package.json
- examples/main-react/scripts/integration.js
- examples/main-vue/vue.config.js
- examples/react16/package.json
- examples/react16/src/App.js
- examples/react16/src/Font.js
- packages/wujie-core/__test__/integration/common.ts
- packages/wujie-core/__test__/integration/font.test.ts
- packages/wujie-core/jest-puppeteer.config.js
- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/sandbox.ts
- packages/wujie-core/src/shadow.ts
- packages/wujie-core/src/utils.ts
- packages/wujie-doc/docs/question/README.md
- 框架将子应用的`@font-face`放到`shadow`外部执行，注意子应用的自定义字体名和主应用的自定义字体名不能重复否则可能覆盖
- 关联issue #28
> fix: 修复子应用字体无法加载的问题 

- examples/main-react/src/index.css
- examples/main-vue/src/App.vue
- examples/react16/src/Font.js
- examples/react16/src/styles.css
- packages/wujie-core/__test__/integration/font.test.ts
- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/entry.ts
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/plugin.ts
- packages/wujie-core/src/sandbox.ts
- packages/wujie-core/src/shadow.ts
- packages/wujie-core/src/template.ts
- packages/wujie-core/src/utils.ts
- packages/wujie-doc/docs/api/startApp.md
- packages/wujie-doc/docs/guide/plugin.md
- packages/wujie-doc/docs/question/README.md
- 特性：框架通过内置 plugin 将子应用样式中相对地址默认转换成绝对地址
- 关联issue：
#27
#25 
#19
> feat: 将子应用样式中相对地址默认转换成绝对地址

- packages/wujie-core/src/proxy.ts
- 特性
子应用的 window.window !== window 导致在 zepto.js 中调用 $(window).width() 出错，修复了window.window === window 这个判断
- 关联issue 
#40
> fix: 修复子应用window.window指向问题

- packages/wujie-react/index.d.ts
修复或者说补充 `wujie-react` 组件 props 的 type 类型，补充了 `prefix` `activated` `deactivated` `loadError`。
> fix(react): correct the type of wujie-react

- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-doc/docs/guide/plugin.md
- packages/wujie-doc/docs/guide/variable.md
- packages/wujie-doc/docs/question/README.md
- 特性
- 子应用的 window.window === window 为true
- 子应用通过`window.__WUJIE_RAW_WINDOW__`获取真实 window
- 关联issue
#40
> feat: 子应用判断window.window为window

- README.md
- examples/vue2/src/main.js
- examples/vue2/src/pageLifeTest.js
- packages/wujie-core/__test__/integration/pageEvent.test.ts
- packages/wujie-core/src/common.ts
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/sandbox.ts
- packages/wujie-core/src/utils.ts
- 特性
1、修复子应用在加载的过程中，DOMContentLoaded事件、load事件、readystatechange事件无法触发的问题
2、修改README
- 关联issue
#49 #43
> fix: 修复子应用加载页面生命周期无法触发

- packages/wujie-core/__test__/integration/font.test.ts
- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/sandbox.ts
- 特性
1、集成测试中 Tdesign icon 更新版本，导致测试用例失败
2、执行队列没有判空导致测试用例失败
3、refactor 一下代码
- 关联issue
#85 #80
> fix: 修复集成测试失败

- packages/wujie-core/src/plugin.ts
https://github.com/Tencent/wujie/blob/master/packages/wujie-core/src/plugin.ts#L57
The default plugin contains a transform for css url(), which should only apply for url path, but not all other url() valid type such as: `url(data:image/png;base64,iRxVB0…);`
- The problem with the current implementation is that it replaces any ["'] in the data url, this shouldn't happen.
- This PR adds an exclude for url(data:) css in default css Loader
- This PR also refactor the regex to replace the url directly
> fix(plugin): fix cssLoader to exclude a data URL

- packages/wujie-core/__test__/unit/plugin.test.ts
- packages/wujie-core/src/plugin.ts
- packages/wujie-core/src/utils.ts
- 特性
修复之前`<a href = "">`标签的 href 为空或者是 hash 地址时，也被转换成了绝对地址的问题
- 关联issue
#107
> fix: 修复空连接或者hash链接也被转换成绝对地址

- packages/wujie-core/__test__/integration/common.ts
- packages/wujie-core/__test__/integration/proxy.test.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/utils.ts
-  [x] 提交符合commit规范
-  [x] `npm run test`通过
- 特性  修复 window 被 proxy 代理后，引起的作用域绑定错误。
-  关联issue [issue #102](https://github.com/Tencent/wujie/issues/102)
> fix: 修复window被proxy,导致作用域错误

- packages/wujie-core/src/utils.ts
- 特性
如果是hash的场景就没有转化为绝对路径，在`<a>`元素锚点是正常的，但是对于hash路由还是需要转化成绝对路径
- 关联issue
#136
> fix: 修复绝对路径对hash路由的影响

- packages/wujie-core/src/common.ts
- 特性
由于框架将document的scroll绑定到主应用的document上，导致react16的合成事件onscroll无法触发，去除这部分逻辑
- 关联issue
#143
> fix: 修复react16 scroll合成事件无法触发问题

- packages/wujie-core/src/proxy.ts
- 特性
window.location.href 、host 等都被代理到子应用的 href、host，导致 locaiton.replace 需要修改回来防止将 iframe 沙箱刷掉
- 关联issue
#151
> fix: 修复react hash 模式下异常

- packages/wujie-core/src/index.ts
- 特性
在开发setupApp的时候，preloadApp的自定义fetch没有添加上，导致预加载的自定义fetch出现问题
- 关联issue
#149
> fix: 修复preload 没有使用自定义fetch

- packages/wujie-core/src/shadow.ts
- 特性
由于 head 和 body 元素在每次切换的时候都需要复用，防止被缓存。切换子应用时需要将 template 反复的插入到这两个元素中，而其 appendChild 和 insertBefore 已经被劫持过，导致 template 里面的样式被反复推入缓存样式表内
所以 template 反复的插入到这两个元素中采用的 appendChild 为原生而非劫持的方法
- 关联issue
- #161
> fix: 修复子应用切换模板样式重复问题

- docs/api/preloadApp.md
- docs/api/startApp.md
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/index.ts
> fix: 修复async脚本导致脚本执行顺序错乱问题

- examples/react16/src/Location.js
- examples/react17/src/Location.js
- examples/react17/src/State.js
- examples/vite/src/views/Location.vue
- examples/vue2/src/views/Location.vue
- examples/vue3/src/views/Location.vue
- packages/wujie-core/__test__/integration/href.test.ts
- packages/wujie-core/src/effect.ts
> fix: 修复异步JavaScript文件加载异常

- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/template.ts
- 特性
通过手动触发的方式触发外联脚本和外联转内联脚本的onload事件
- 关联issue
#210
> fix: 修复esm和jsIgnores脚本的onload事件没有触发

- docs/guide/plugin.md
- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/iframe.ts
> feat: 钩子appendOrInsertElementHook添加原生元素参数

- docs/guide/jump.md
- packages/wujie-core/src/common.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/sandbox.ts
- 特性
由于需要使用原生的 createElement 和 createTextNode方法，需要从主应用获取，代码采用了 window.top.Docuemnt.prototype.xxx 来获取导致主应用内嵌在 iframe 中报错
- 关联issue
> fix: 修复无界主应用内嵌在iframe内部报错

- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/sandbox.ts
当主应用需要拦截原生的`createElement`时，自然会将`createElement`的`this`指向主应用的`document`。
然而，目前在`wujie`的`proxyDocument`中，是统一使用主应用的`createElement`，并尝试将`this`指向`iframe`的`document`。
在使用过程中发现，如果`wujie`的`proxyDocument`中，执行了被主应用改写过的`createElement`导致`this`最终指向主应用的`document`，会导致子应用内的节点，`element instanceof HTMLElement` 得到`false`。
因此，在`wujie`的`proxyDocument`中改为使用同域`iframe`的`createElement`方法。
- 特性
- 关联issue
#274
> fix: 兼容主应用拦截原生的createElement

- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/sandbox.ts
- packages/wujie-core/src/shadow.ts
- packages/wujie-core/src/sync.ts
- packages/wujie-core/src/utils.ts
在子应用需要自动转为iframe渲染的场景（如降级、替换整个location.href），用于渲染的iframe目前的style只有width: 100%; height:100%。
希望能增加一个参数，方便主应用将一些常用的样式（如minHeight、minWidth）传递给用于渲染的iframe。
- 特性
- 关联issue
#271
> feat: 增加degradeAttrs参数用于控制降级时的Iframe属性

- docs/api/preloadApp.md
- docs/api/setupApp.md
- docs/api/startApp.md
- packages/wujie-core/src/entry.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/utils.ts
> feat: 添加子应用可以直接读取html的能力

- packages/wujie-core/src/sandbox.ts
- packages/wujie-core/src/shadow.ts
- packages/wujie-core/src/sync.ts
- 特性
降级模式下，子应用的dom iframe 的 html 是非标准模式，需要修改成标准模式 
- 关联issue
#302
> fix: 修复降级场景下文档非标准模式问题

- packages/wujie-core/src/iframe.ts
对于一些使用了`iframe`的主应用/子应用，可能会通过修改`document.domain`的方式指定二级域以放宽“同源限制”，从而操作`iframe`内的文档。
然而这个方式会对`wujie`的同域`iframe`产生影响：在创建`iframe`后的极短时间内移除掉注入到`iframeWindow`上的属性，从而导致子应用加载失败。
我怀疑这与[iframe错误文档陷阱](https://zh.javascript.info/cross-window-communication#iframe-cuo-wu-wen-dang-xian-jing)有关。
在验证的过程中发现以下细节：
1、不管是否修改过`domain`，如果是在`iframe`的`document`真正准备好之后往`iframeWindow`上注入属性，则不会被移除。
2、不管是否修改过`domain`，`iframe`错误文档陷阱都存在，但如果主应用修改过`domain`，错误文档停留的时间明显更长。
3、不修改`domain`场景下，没有移除`iframeWindow`属性的现象
因此，这个PR尝试兼容`domain`的修改，兼容后与`iframe`对`domain`的要求基本一致：
1、如果是主应用希望修改`domain`放宽“同源限制”
主应用中原来`iframe`的用法不变。
主应用可正常使用`wujie`加载子应用，且子应用的`domain`自动变为主应用修改的`domain`
2、如果是`wujie`加载的某个子应用希望修改`domain`，并在子应用内使用`iframe`
应该改为在`wujie`主应用中修改`domain`，子应用则可以不改（会继承主应用的）。
- 特性
- 关联issue
#245 #71
> fix: 适配domain修改

- packages/wujie-core/src/entry.ts
子应用 html 请求失败后，切换子应用后，失败的子应用不会重新发起 html 请求
- 特性
- 关联issue
> fix: 修复子应用html加载失败后无法重试

- packages/wujie-core/src/index.ts
- 特性
非预执行场景下的预加载，js资源没有提前加载下来
- 关联issue
> fix: 修复预加载js资源没有下载

- packages/wujie-core/src/index.ts
所以似乎没有必要：`sandbox.preload` 已经是Promise，`Promise.resolve()` 只会返回它自身。
- 特性
- 关联issue
> chore: remove useless Promise.resolve()

- packages/wujie-core/src/iframe.ts
-  [x] 提交符合commit规范
-  [x] `npm run test`通过
火狐浏览器的bug，如下
https://bugzilla.mozilla.org/show_bug.cgi?id=941146
在css容器设置为display:none下，对canvas.getContent().font赋值会报`NS_ERROR_FAILURE` 错误 ，导致canvas无法渲染成功
- 特性
- 关联issue 
`issue #428`
> fix: 修复在firefox下echarts、g6等canvas无法显示的问题(#428)

- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/utils.ts
> fix: 修复子应用媒体元素资源路径错误的问题

- packages/wujie-core/src/proxy.ts
解决在chrome 85以下版本，子应用执行window.window报错
- 特性
- 关联issue
#280
> fix: 修复chrome85以下版本window.window报错问题

- .gitignore
- docs/.vitepress/config.ts
- docs/.vitepress/theme/index.ts
- docs/.vitepress/theme/styles/DocSearch.css
- docs/.vitepress/theme/styles/vars.css
- docs/package.json
- docs/wujie/components/data.ts
- pnpm-lock.yaml
- feat(doc): add algolia search with style
- chore(doc): change demo website
- chore(doc): script docs:dev --port 9765(wujie ascii code)  prevent port conflicts
> feat(doc): add algolia search

- docs/.vitepress/config.ts
- docs/.vitepress/theme/styles/DocSearch.css
- docs/guide/share.md
- packages/wujie-core/src/plugin.ts
- 特性
修复chrome111 html的默认属性view-transition-name为 none
- 关联issue
#448
> fix: 修复子应用html默认属性

- .gitignore
- packages/wujie-core/src/iframe.ts
在阅读源码时，看到 `iframeGenerator`  只做了 2 个事情：
+ `patchIframeVariable`
+ `stopIframeLoading`
但实际上，更主要的部分，是在  `initIframeDom` 函数中，这个函数写在 `stopIframeLoading`，`stopIframeLoading` 实际作用跟函数名称，应该把 `initIframeDom` 放到外边
> refactor: 优化 stopIframeLoading，让逻辑更清晰，增加可读性

- packages/wujie-core/src/common.ts
- packages/wujie-core/src/constant.ts
- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/utils.ts
`wujie`重写了子应用`ShadowRoot`的`head.appendChild`方法，将子应用插入的`script`转移到了同域`Iframe`内的`head`。然而`contains`和`removeChild`方法依然指向的是`ShadowRoot`，这导致子应用在插入`script`后无法通过`contains`判断该`script`的存在，也无法通过`document.head.removeChild`将其移除。
此PR调整了`ShadowRoot`的`head.contains`、`contains`、`head.removeChild`这三个方法，尝试适配子应用对`script`的处理。适配后效果如下：
```
const script = document.createElement('script')
script.type = 'text/javascript'
script.async = true
script.src = 'test.js'
document.head.appendChild(script)
console.log(document.contains(script)) // false, [wujie warn]: 目标Script尚未准备好或已经被移除 <script wujie='1679239314179'/>
console.log(document.head.contains(script)) // false, [wujie warn]: 目标Script尚未准备好或已经被移除 <script wujie='1679239314179'/>
// 等待wujie的script加载完成
setTimeout(() => {
console.log(document.contains(script)) // true …
```
> fix: 适配子应用处理script标签

- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/utils.ts
子应用调用document.head.appendChild插入script脚本，如果是外链脚本无界会将这个脚本转化为内联脚本来执行，但是用户如果连续appendChild多个有依赖关系的脚本，无界并没有保持这个依赖关系，而是哪个脚本先下载完就执行那个脚本，所以这次添加了一个dynamicScriptExecStack的栈来保持依赖关系，并且依然可以并发的请求，只是最后执行阶段保持依赖关系
- 特性
- 关联issue
#465
> fix: 修复appendChild执行顺序的问题

- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/template.ts
- 特性
不管是外联脚本还是动态脚本，无界会将这些脚本转化为内联脚本，并且在这个过程中抛弃了原始脚本上的属性，比如id、data-xxx等等，本次pr会将原始属性保留到内联脚本中，比如：
```javascript
<script id="myscript" data-message="hello" src="xxxxxxx"></script>
```
会最终转化成：
```javascript
<script id="myscript" data-message="hello"> yyyyyyy </script>
```
可以通过 document.getElementByid(myscript) 或者 document.querySelector('#myscript')获取转化后的脚本
- 关联issue
#464 #374
> fix: 修复script脚本属性丢失的问题

- examples/main-react/src/index.css
- examples/main-vue/src/App.vue
- packages/wujie-core/src/constant.ts
- packages/wujie-core/src/index.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/utils.ts
- 特性
在初始化子应用 iframe 的过程中，跑了主应用的代码，导致类似`Cannot read properties of undefined (reading 'firstElementChild')`这样的报错，这里框架全部主动报错来提示用户
- 关联issue
> fix: 运行主应用代码主动报错

- packages/wujie-core/src/iframe.ts
当我使用第三方库时，发现它内部未传递 `addEventListener` 事件处理函数，导致报错，我在 ifrane.ts 中对它进行了为空判断
> fix(iframe): 修复 handler 为 undefined 时添加到 handlerCallbackMap 报错

- packages/wujie-core/src/iframe.ts
- [ x] `npm run test`通过
在多层嵌套情况下，iframeWindow的__WUJIE_RAW_DOCUMENT_QUERY_SELECTOR__等真实dom函数未指向当前iframe实例下，所以无法找到渲染根节点，造成嵌套多层的应用部分无法渲染
- 关联issue issue #487
> fix(iframe): 修复多层嵌套找不到渲染节点问题

- packages/wujie-core/src/effect.ts
- packages/wujie-core/src/iframe.ts
- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/template.ts
- 特性
修复了子应用空白的问题，该问题是因为代码  iframeWindow.__WUJIE_RAW_DOCUMENT_QUERY_SELECTOR__ 绑定了iframeWindow.document 导致在嵌套的 子应用内使用 call 无效
修复了link的 id 丢失的问题 
- 关联issue
#487  #485
> fix: 修复子应用嵌套页面空白问题

- examples/main-vue/src/App.vue
- examples/react17/src/Communication.js
- packages/wujie-core/src/common.ts
- packages/wujie-core/src/iframe.ts
- pnpm-lock.yaml
- 特性
- 关联issue: https://github.com/Tencent/wujie/issues/549#issuecomment-1556119558
> fix: 子应用window事件监听增加message事件，增加事件监听target可选参数

- packages/wujie-core/src/iframe.ts
在 #483 中，未进行后续的handler有效判断，导致后续执行错误，当handler未传递时，应停止执行后续的操作。
- 特性
- 关联issue #483
> fix(iframe): 修复 handler 为 undefined 时执行 addEventListener 错误

- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/utils.ts
子应用往全局定义一个不可写且不可配置的数据属性，当这个属性为函数时，在`wujie`内会调用失败，并报错：
```
Object.defineProperty(window, 'testPro', {
configurable: false,
writable: false,
value: function() {
return 'testValue'
}
})
console.log(window.testPro()) // TypeError: 'get' on proxy: property 'testPro' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value
```
这是因为子应用通过`wujie`的`proxyWindow`读取这个属性时，`wujie`发现是个函数，会尝试改变其`this`指向并返回新的执行结果。然而对于不可写且不可配置的数据属性，ES要求返回原值：
https://262.ecma-international.org/8.0/#sec-proxy-object-internal-methods-and-internal-slots-get-p-receiver
> NOTE [[Get]] for proxy objects enforces the following invariants:
> - The value reported for a property must be the same as the value of the corresponding target object property if the target object …
> fix: 兼容子应用定义不可修改的全局函数

- packages/wujie-core/src/common.ts
wujie子应用中使用`window.addEventListener('error', fn)`无法进入监听函数，故增加此行代码
> fix: 修复wujie子应用无法监听error事件

- packages/wujie-core/src/effect.ts
- 修复 effect.ts 中 appendChildOrInsertBefore 方法插入 ignore 元素时，应该插入目标元素而不是新建 link 元素做替换，从而保证目标元素的上下文
> fix: appendChildOrInsertBefore effect ignore css error

- packages/wujie-core/src/constant.ts
- packages/wujie-core/src/proxy.ts
与[#547](https://github.com/Tencent/wujie/pull/547)想法一致，在子应用中`document.getElementById`会被代理成`querySelector`，而`querySelector`并不支持特殊字符的传递，比如当使用`document.getElementById('aa/1')`，会报错
正常情况下`document.getElementById` 应该支持特殊字符，并且找不到的时候返回`null`，并不期望会报错；因此需要对`document.getElementById`代理做兼容异常处理
> fix(proxy): protect the program when getElementById throws an exception error

- packages/wujie-react/index.js
- 特性： 修复wujie-react更新属性 url 子应用不刷新的问题。
- 关联issue： https://github.com/Tencent/wujie/issues/688
> fix: wujie-react watch props change, restart app

- packages/wujie-core/src/iframe.ts
某些页面使用降级模式，发现一些事件监听器丢失。
经排查，此处：
recordEventListeners：
if (!elementListenerList.find((listener) => listener.handler === handler)) {
这个判断只判断handler一样就是认为是相同事件监听器，不进行缓存，根据addEventListener的参数，type、handler、options、useCapture、wantsuntrusted五元组共同组成不同事件监听器，因此type不同、handler相同也应该缓存下来。
改为：
if (!elementListenerList.find((listener) => listener.type === type && listener.handler === handler))
应该能兼容99%的情况。
fixes #757
> fix: 修复降级模式会丢失事件监听器

- packages/wujie-core/src/common.ts
- 问题描述：
在子应用里面使用常规 webcompents 组件如 [omi](https://github.com/Tencent/omi)、[fast](https://github.com/microsoft/fast)、[ionic-framework](https://github.com/ionic-team/ionic-framework) 等的时候，会出现组件无法加载的情况，提示如下报错：
- 原因
该问题是因为常规 webcompents 组件为了分离样式和代理，会通过 `new CSSStyleSheet()` 的方式将 css 样式添加到 adoptedStyleSheets  上，可以不使用组件库直接通过如下方法复现：
在子应用里面添加如下代码
```javascript
const stylesheet = new CSSStyleSheet();
stylesheet.replaceSync('body { background: red !important; }')
document.adoptedStyleSheets = [...document.adoptedStyleSheets, stylesheet];
```
正常使用 CSSStyleSheet 是没有问题的，但是该属性有个特性：
> Set sheet’s Constructor document to the associated Document for the current global object. [css-style-sheets](https://www.w3.org/TR/cssom-1/#css-style-sheets)
> The Window object has an associated Document, which is a …
> fix: 修复子应用无法使用 WebComponent 组件库，提示 adoptedstylesheets 问题

- packages/wujie-core/src/common.ts
> fix: 修复子应用无法使用 WebComponent 组件库，提示 adoptedstylesheets 问题 (#771)

- packages/wujie-core/src/common.ts
- packages/wujie-core/src/proxy.ts
- 特性
使用vite-legacy-plugin插件打包后的兼容文件，会存在如下script代码：
```
<script
crossorigin
id="vite-legacy-entry"
data-src="https://tracker-online.oss-cn-beijing.aliyuncs.com/scripts/index-legacy.7f2776b7.js"
>
System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'));
</script>
```
在wujie非降级模式下，对`getElementById`这个api做了script获取的兼容；而在降级模式下，并没有做兼容，导致`getElementById`的查找范围只有iframe sandbox 之中，而其上代码需要获取放在iframe contentDocument中的script标签，因为作用域不同，导致无法获取到。
我的修改是优先在 iframe sandbox 中查找元素，如果没有查找到则去iframe contentDocument查找，从而保证了可以找到script标签
- 关联issue
> fix: 修复在降级情况下无法加载vite使用vite-legacy-plugin打包出的js文件

- packages/wujie-core/src/shadow.ts
- [- ] 提交符合commit规范
- [ x] `npm run test`通过
- 关联issue
- 修复 https://github.com/Tencent/wujie/issues/908 的问题
> fix: 修复 子应用 html 上的属性会被丢失的问题(#908)

- packages/wujie-core/src/common.ts
wujie在给子应用的window事件做监听代理时，少配置了onerror 和 onunhandledrejection，导致子应用无法正常监听这2个事件
> fix: appWindowOnEvent 增加 onerror and onunhandledrejection 事件

- packages/wujie-react/index.js
- 特性
处理 React 组件重复渲染时 wujie.startApp() 的异步竞争导致的问题
- 关联issue
见 https://github.com/Tencent/wujie/pull/599
> fix: 修复wujie-react重复渲染时保活模式输出undefined

- packages/wujie-core/src/iframe.ts
- 特性
一些第三方库内部会使用
```
const script = document.createElement("script");
script.onload = function () {
document.body.removeChild(script);
};
document.body.appendChild(script)
```
这种形式关联自己的脚本资源，但由于wujie劫持了子应用的Node.prototype.appendChild并改变了脚本的实际执行环境，所以在removeChild的时候会报错阻塞脚本执行。
所以添加了对子应用removeChild的劫持，在调用时判断目标Node是否还与Document连接，并尝试使用Node.parentNode.removeChild进行移除。
- 关联issue
https://github.com/Tencent/wujie/issues/524
> fix: 修复通过appendChild添加的外部脚本中使用document.body.removeChild移除脚本报错阻塞代码执行的问题

- packages/wujie-core/src/proxy.ts
- packages/wujie-core/src/utils.ts
- 特性
之前多个子应用共享缓存的全局对象，会导致多个子应用拿到的都是第一个子应用缓存的全局对象（Window、Location、ShadowRoot、Document）
现在修改成多个子应用缓存各自的全局对象
- 关联issue
[子应用使用CKEditor5富文本编辑器，改变url的query参数重新加载后光标异常 #768](https://github.com/Tencent/wujie/issues/768)
[页面中使用多个子应用时，子应用 getSelection() 指向错误 #770](https://github.com/Tencent/wujie/issues/770)
> fix: 修复多个子应用启动，拿到的全局对象缓存都是第一个子应用全局对象的bug

- packages/wujie-core/src/sandbox.ts
在afterUnmount的回调函数中，使用 destroyApp 方法时，bus 属性为null ，调用$clear()会报错,我们的场景相对复杂一点，需要考虑保活和不保活两种场景，不保活时需要销毁原来的应用，否则无法再次打开，所以这里需要加一个判断进行兼容
- 特性
- 关联issue
> fix: 在afterUnmount的回调函数中，使用 destroyApp 方法时，bus 属性为null ，调用$clear()会报错

- packages/wujie-core/src/plugin.ts
- 复现路径
子应用编写以下样式，base64图片中svg的填充路径被替换
```css
/* 替换前 */
background: url(data:image/svg+xml;charset=utf-8,<svg><path fill='url(#a)'></path></svg>);
/* 替换后 */
background: url(data:image/svg+xml;charset=utf-8,<svg><path fill='url(replaceHost#a)'></path></svg>);
```
- 原因
原先正则` /(url\((?!['"]?(?:data):)['"]?)([^'")]*)(['"]?\))/g;`，会先忽略data开头，导致匹配到内部的`fill='url(#a)'`中的`#a`进行路径替换
- 解决方案
修改正则表达式为`/url\((['"]?)((?:[^()]+|\((?:[^()]+|\([^()]*\))*\))*)(\1)\)/g`，先匹配`url(xxx)`内的xxx，包含嵌套括号等。然后再判断是否为base64.
```javascript
const urlReg = /url\((['"]?)((?:[^()]+|\((?:[^()]+|\([^()]*\))*\))*)(\1)\)/g;
return code.replace(urlReg, (_m, pre, url, post) => {
const base64Regx = /^data:/;
const isBase64 = base64Regx.test(url);
/** 如果匹配到data:前缀，则认为是base64文件，直接不进行路径替换吧 */
if (isBase64) {
return _m;
}
return …
```
> fix: 修复css中图片url解析错误

- packages/wujie-core/src/shadow.ts
- 使用 DOMParser渲染的HTML DOM使其丢失了沙箱上下文，导致 #921 。
- 修复后，使用 1.0.22 以前的方法 `document.createElement("html")` 渲染出 HTML 元素，而 `DOMParser` 只作为 template 的解析器，将解析出的 html 标签属性赋值到有沙箱上下文的 HTML 元素。
> fix(shadow): 修复DOMParser渲染html元素丢失沙箱上下文的问题 #921

- packages/wujie-core/src/proxy.ts
> fix: 修复在 sandbox.document.getElementById 无法查询到时, 使用 iframe 调用回到 proxy 导致死循环

- packages/wujie-core/src/index.ts
> fix: 将 preOpstions 类型提示中 url 变为可选项

- packages/wujie-react/index.js
- packages/wujie-vue2/index.js
- packages/wujie-vue3/index.js
- 特性 
支持设置包围的div元素的样式
`
<WujieReact
style={{
overflow: "auto",
}}></WujieReact>
`
> feat: react，vue组件支持设置包围的div组件style
