packages/wujie-core/src/iframe.ts

fixed: 子应用给on事件赋值报错

---

packages/wujie-core/src/effect.ts

如果子应用里通过类似如下的方式动态引入 `type=module` 的脚本，wujie目前是会报错的：
```js
(function() {
let script = document.createElement('script');
script.type="module"
script.crossorigin=""
script.src = 'https:/xxx.com/xxx.js';
document.getElementsByTagName('head')[0].appendChild(script);
})();
```
这个fix在处理动态引入的脚本的时候补充了 `module` 属性

fix: dynamic append js-module script error

---

packages/wujie-doc/docs/guide/variable.md

docs: 修复拼写错误

---

packages/wujie-react/index.d.ts

`wujie-react` 包的类型声明存在问题，插件属性修复为 `plugins`。

fix(React): 修复 wujie-react 组件 Props 声明错误

---

examples/main-react/src/fetch.js
examples/main-vue/src/fetch.js
packages/wujie-core/src/iframe.ts
packages/wujie-core/src/index.ts
packages/wujie-core/src/plugin.ts
packages/wujie-core/src/sandbox.ts
packages/wujie-core/src/shadow.ts
packages/wujie-core/src/utils.ts

- 特性 
修复url解析错误问题
顺便修复预加载后默认插件不生效问题
- 关联issue
#22

fix: 修复url解析错误问题

---

README.md

docs: 文档添加动机

---

examples/main-react/public/index.html
examples/main-vue/public/index.html
examples/vite/src/main.ts
examples/vite/src/router/index.ts
examples/vue2/src/main.js
examples/vue2/src/router/index.js
packages/wujie-doc/docs/guide/start.md
packages/wujie-doc/docs/question/README.md

- 特性
1、修改demo和文档，规范子应用单例模式下在__WUJIE_MOUNT路由实例需要新建
2、针对iframe初始化的时候加载运行了主应用代码问题，给出解决方式
- 关联issue
#54

docs: 修改示例和文档

---

examples/main-react/src/App.js
examples/main-react/src/hostMap.js
examples/main-react/src/index.css
examples/main-react/src/index.js
examples/main-react/src/pages/All.js
examples/main-react/src/pages/Angular12.js
examples/main-react/src/pages/React16.js
examples/main-react/src/pages/React17.js
examples/main-react/src/pages/Vite.js
examples/main-react/src/pages/Vue2.js
examples/main-react/src/pages/Vue3.js
examples/main-vue/src/App.vue
examples/main-vue/src/hostMap.js
examples/main-vue/src/main.js
examples/main-vue/src/router/index.js
examples/main-vue/src/views/Angular12.vue
examples/main-vue/src/views/Multiple.vue
examples/main-vue/src/views/React16.vue
examples/main-vue/src/views/React17.vue
examples/main-vue/src/views/Vite.vue
examples/main-vue/src/views/Vue2.vue
examples/main-vue/src/views/Vue3.vue
examples/main-vue/vue.config.js
examples/react16/src/hostMap.js
examples/react16/src/nest.js
examples/react17/src/App.js
examples/vue3/src/App.vue
packages/wujie-core/src/proxy.ts

- 特性
添加主应用多个菜单栏对应子应用不同页面demo
子应用window.window修复成依然指向原生window
- 关联issue
#46

docs: 增加子应用多菜单展示demo

---

examples/main-react/src/index.js
examples/main-vue/src/main.js
packages/wujie-core/src/index.ts
packages/wujie-doc/docs/.vuepress/config.js
packages/wujie-doc/docs/README.md
packages/wujie-doc/docs/api/setupApp.md
packages/wujie-doc/docs/guide/start.md
packages/wujie-doc/docs/pack/README.md
packages/wujie-doc/docs/pack/react.md
packages/wujie-react/index.d.ts
packages/wujie-react/index.js
packages/wujie-vue2/index.d.ts
packages/wujie-vue2/index.js
packages/wujie-vue3/index.d.ts
packages/wujie-vue3/index.js

- 特性
createApp 和 vue 的 api 重名，改成 setupApp
- 关联issue
#65

feat: 将createApp改名为setupApp

---

CONTRIBUTING.md
package.json

- 特性
- optimize the developer to start the project，is this a good way to help developers start the project quickly?
- 关联issue

chore(deps): optimize the way to start the project

---

packages/wujie-core/src/effect.ts

fix: 修复style标签被重复代理的情况

---

.husky/pre-commit

commitlint 使用npx调用本地lerna模块，因为我们现在依赖中不需要用户全局安装lerna，目前如果没有全局安装会报错

fix(precommit): call the local lerna module

---

.github/workflows/main.yml
examples/angular12/CHANGELOG.md
examples/main-react/CHANGELOG.md
examples/main-vue/CHANGELOG.md
examples/react16/CHANGELOG.md
examples/react17/CHANGELOG.md
examples/vite/CHANGELOG.md
examples/vue2/CHANGELOG.md
examples/vue3/CHANGELOG.md
packages/wujie-core/CHANGELOG.md
packages/wujie-doc/CHANGELOG.md
packages/wujie-react/CHANGELOG.md
packages/wujie-vue2/CHANGELOG.md
packages/wujie-vue3/CHANGELOG.md

- 特性
1、添加changelog
2、修复发包脚本错误
- 关联issue
#77

feat: 添加changelog

---

docs/.vitepress/config.ts
docs/question/index.md

- 特性
添加图片相对地址错误的修复方式
- 关联issue
#99 #93

chore(docs): 添加新问题

---

docs/wujie/components/wujie-connect.vue
docs/wujie/components/wujie-online.vue
docs/wujie/index.md

- 特性
新增点击链接 url 回显到 input 输入框中
- 关联issue

feat(docs): 实时体验页面, url 回显功能

---

.github/workflows/main.yml
docs/wujie/components/wujie-connect.vue
docs/wujie/components/wujie-online.vue
examples/main-react/src/hostMap.js
examples/main-react/src/index.js
examples/main-vue/src/hostMap.js
examples/main-vue/src/main.js
packages/wujie-core/__test__/integration/font.test.ts
packages/wujie-core/__test__/integration/host.test.ts
packages/wujie-core/__test__/integration/utils.ts
packages/wujie-core/src/effect.ts
packages/wujie-core/src/iframe.ts

- 特性
1、修复twind切换应用样式丢失的问题
2、修改demo的attrs属性
- 关联issue
#116

fix: 修复使用twind切换应用样式丢失的问题

---

packages/wujie-core/src/effect.ts
packages/wujie-core/src/iframe.ts

- 特性
修复svg在append到元素之后ownerdocument失效问题
- 关联issue

fix: 修复svg在append到元素之后ownerdocument失效问题

---

packages/wujie-core/src/shadow.ts

修正 destroy 后 unmount 报错

---

packages/wujie-react/index.js

- 特性
- 关联issue
A simple refactor of `packages/react/index.js`.

refactor(react-index.js): improve readability

---

docs/.vitepress/config.ts
docs/guide/demo.md

- 特性
1. 新增定制化demo cli 修改文档
2. 新增vitepress config 最后更新时间配置

feat(docs): add Customized demo cli

---

packages/wujie-vue3/index.js

解决 wujie-vue3 在使用时 vue 警告 destroy 重复声明问题

fix: 解决 data 与 methods 存在相同属性导致 vue 警告

---

packages/wujie-core/src/entry.ts

fix: 修复js文件下载失败会导致子应用运行失败

---

packages/wujie-core/src/sandbox.ts

- 特性
修复destroyAPP没有删除子应用dom的问题
- 关联issue
#170

fix: 修复destroy没有清除子应用dom的问题

---

examples/main-react/package.json
examples/main-vue/package.json
examples/react16/package.json
packages/wujie-react/package.json
packages/wujie-vue2/package.json
packages/wujie-vue3/package.json

依赖使用 pnpm workspace 协议

---

docs/api/setupApp.md
packages/wujie-core/src/index.ts

fix: 修复cacheOptions类型不正确的问题

---

docs/guide/mode.md

fix: edit mode message

---

packages/wujie-core/src/proxy.ts

fix: 修复子应用location.origin为主应用地址问题

---

docs/api/wujie.md
docs/guide/information.md
docs/guide/variable.md
packages/wujie-core/src/sandbox.ts

refactor(types): remove undefined

---

docs/api/preloadApp.md
docs/api/startApp.md
docs/guide/plugin.md
packages/wujie-core/src/effect.ts
packages/wujie-core/src/iframe.ts
packages/wujie-core/src/index.ts

feat: 插件添加appendOrInsertElementHook钩子

---

README.md

docs: Global Vue API is changed to use an application instance in Vue 3

---

packages/wujie-core/src/common.ts
packages/wujie-core/src/proxy.ts
packages/wujie-react/index.d.ts

fix: 修复内嵌场景下createElement重复覆盖的问题

---

packages/wujie-core/src/proxy.ts

- 关联issue
https://github.com/Tencent/wujie/issues/262

fix: 修正其他document调用获取元素函数无法获取的问题

---

packages/wujie-core/src/common.ts

- 特性
- 关联issue
https://github.com/Tencent/wujie/issues/304

fix: 子应用KeyboardEvent不生效

---

packages/wujie-core/src/sandbox.ts

fix: 修复保活模式下路由参数丢失的问题

---

docs/guide/index.md

docs: Update a word.

---

docs/api/preloadApp.md
docs/api/startApp.md
docs/guide/plugin.md
packages/wujie-core/src/iframe.ts
packages/wujie-core/src/index.ts

- 特性
框架在创建元素的时候，会对元素的一些属性进行劫持修改，此处提供出一个钩子，也方便用户个性化的进行劫持修改
- 关联issue
#345

feat: 添加patchElementHook钩子

---

packages/wujie-vue2/index.d.ts

在 vue+ts 项目中使用 `wujie-vue2` 时 `Vue.use(WujieVue)` 会有类型错误
- 特性
- 关联issue

fix(chore): 修复 Vue.use(WujieVue) 时类型错误

---

packages/wujie-core/src/effect.ts

fix: ignore的 link 未正确设置

---

packages/wujie-react/index.js
packages/wujie-vue2/index.js
packages/wujie-vue3/index.js

feat: wujie dom support style props

---

packages/wujie-vue3/index.d.ts

- 特性 
修复 vue3 组件注册时类型错误
- 关联issue
[wujie-vue3 组件局部注册时类型错误](https://github.com/Tencent/wujie/issues/393)

fix: 修复 vue3 组件注册时类型错误 (#393)

---

docs/wujie/components/data.ts
docs/wujie/components/wujie-connect.vue
docs/wujie/components/wujie-online.vue

- Remove demo sites that prohibit cross-domain online experience
- The new version of react, a new wuji react demonstration website, will experience better in demo.

chore(docs):   optimize the online experience interface remove prohibited cross-domain websites

---

packages/wujie-core/src/constant.ts
packages/wujie-core/src/effect.ts
packages/wujie-core/src/iframe.ts
packages/wujie-core/src/shadow.ts
packages/wujie-core/src/utils.ts

- 特性
解决外链js执行顺序不正确的问题
- 关联issue
#424

fix: 修复js执行顺序的问题

---

packages/wujie-core/src/entry.ts

fix: 修复esm脚本执行顺序问题

---

packages/wujie-core/src/constant.ts
packages/wujie-core/src/entry.ts

fix: 修复获取html入口文件时，因为接口异常不能正常触发loadError生命周期

---

packages/wujie-core/src/index.ts
packages/wujie-core/src/sandbox.ts

feat: 修正css时序及重复patch的问题(#568)

---

packages/wujie-react/index.js

fix: 修复wujie-react偶现无法加载子应用元素

---

docs/guide/plugin.md

docs: 调整了几处文字错误

---

packages/wujie-core/src/common.ts

fix: 修改wujie子应用无监听unhandledrejection问题

---

docs/wujie/components/data.ts

chore(doc): remove access fetch error website

---

packages/wujie-core/src/iframe.ts

fix: 兼容部分浏览器script src不可配置

---

.npmrc

- [ x] 提交符合commit规范
- [ x] 文档更改
- [ x] 测试用例添加
- [ x] `npm run test`通过
- 特性
- 关联issue

chore: 删除错误文件

---

packages/wujie-core/src/iframe.ts

- [ x] 提交符合commit规范
- [ x] 文档更改
- [x ] 测试用例添加
- [x ] `npm run test`通过
- 特性
- 关联issue https://github.com/Tencent/wujie/issues/648

fix: 修复在safari下scriptElement的src下不可写的问题

---

docs/.vitepress/theme/index.ts
docs/documate.json
docs/package.json
docs/wujie/components/data.ts
docs/wujie/components/wujie-connect.vue
docs/wujie/components/wujie-online.vue
pnpm-lock.yaml

feat: add AI search

---

packages/wujie-core/src/iframe.ts

- 修改patchDocumentEffect方法中处理document事件中可能引发的内存泄露

feat: 优化处理document专属事件中可能造成内存泄露部分

---

packages/wujie-core/src/utils.ts

fix:修复保活模式 路由query参数丢失 (#295)

---

docs/guide/jump.md

修改了文档-指南-路由跳转底部的handleJump
```diff
function handleJump() {
- window.$wujie?.props.jump({ path: "/pathB" } , `?B=${window.encodeURIComponent("/test")}`});
+ window.$wujie?.props.jump({ path: "/pathB" } , `?B=${window.encodeURIComponent("/test")}`);
}
```
- 特性
- 关联issue

docs: 子应用的点击跳转函数 handleJump语法修正

---

docs/guide/start.md

docs: 子应用更加精准的跨域设置描述

---

docs/.vitepress/config.ts
docs/.vitepress/theme/components/wujie-home.vue

feat: add dark mode support for wuji icon
